title: Daniel Hladík
description: Welcome to my CV
baseurl: ""
url: https://dandee42.github.io./

remote_theme: piazzai/cvless

# site settings
taglong: Welcome to my CV
tagshort: Daniel Hladík

# author settings
author:
  name: Place Holder
  email: username@domain.com
photo: assets/files/photo.jpg
address: Foobar Hall 1.23
phone: +1 234 567 890

# social media links
social:
  github: username
  linkedin: username

# build settings
permalink: pretty
exclude:
  - docker-compose.yml
  - LICENSE
  - README.md
